In [2]:
import numpy as np;

In [4]:
#1. NumPy program to convert Fahrenheit degree to centigrade degree.
farenheit=np.array([100,98.4,96.5,94.2,91.6])
degree=np.array([])
for i in farenheit:
    c=(i-32)*5/9
    #np.append(arr, values)
    degree=np.append(degree,c)
print("Farenheit",degree)
    

Farenheit [37.77777778 36.88888889 35.83333333 34.55555556 33.11111111]


In [6]:
#2.  create a random array with 1000 elements and compute the 
# average, variance, standard deviation of the array elements
arr=np.array([10,20,30,40,50])
mean=arr.mean()
var=arr.var()
std=arr.std()
print("Mean:",mean,"Variance:",var,"Standard deviation:",std)

Mean: 30.0 Variance: 200.0 Standard deviation: 14.142135623730951


In [3]:
#creating a random array using random.randint(low,high,size)
#using np.arange(1,100)
#np.random.shuffle(arrname)

arr1=np.random.randint(0,1000,1000)
mean=arr1.mean()
var=arr1.var()
std=arr1.std()
print("mean:",mean,"Variance:",var,"Standard deviation:",std)

mean: 488.002 Variance: 86220.157996 Standard deviation: 293.63269231473527


In [5]:
arr2=np.arange(1,2000)
print(arr2)
np.random.shuffle(arr2)
print(arr2)
mean=arr2.mean()
std=arr2.std()
var=arr2.var()
print("mean:",mean,"Variance:",var,"Standard deviation:",std)

[   1    2    3 ... 1997 1998 1999]
[ 618 1443 1184 ... 1124  188 1732]
mean: 1000.0 Variance: 333000.0 Standard deviation: 577.0615218501404


In [ ]:
# 3. NumPy program to convert angles from degrees to radians for all elements in a 
# given array
degree=np.array([98.0,95.4,101])
rad=np.deg2rad(degree)
print("Degrees:",degree)
print("radians:",rad)


Degrees: [ 98.   95.4 101. ]
radians: [1.71042267 1.66504411 1.76278254]


In [ ]:
# 4.NumPy program to calculate the difference between neighbouring elements, 
# element-wise of a given array.
arr=np.array([np.random.randint(10,40,10)])
diff=np.diff(arr)
print("Array:",arr)
print("Diff:",diff)


Array: [[32 12 32 24 32 22 31 19 17 23]]
Diff: [[-20  20  -8   8 -10   9 -12  -2   6]]


In [11]:
# 5.NumPy program to sort a given complex array using the real part first, then the 
# imaginary part.
arr = np.array([complex(7,5),complex(4,3),complex(12,2),complex(1,8),complex(1,9)])
sort=np.sort(arr)
print("Array before sorting:",arr)
print("array after sorting:",sort)

Array before sorting: [ 7.+5.j  4.+3.j 12.+2.j  1.+8.j  1.+9.j]
array after sorting: [ 1.+8.j  1.+9.j  4.+3.j  7.+5.j 12.+2.j]


In [14]:
#  6.NumPy program to create a 1D array with random numbers and print the values 
# greater than 4
arr=np.random.randint(low=-40,high=40,size=10)
print(arr)
res =np.where(arr > 4)
print("Elements greater than 4")
for ele in res:
    print(arr[res])

[ 38  17  -2  29  17 -21  38 -27  14   9]
Elements greater than 4
[38 17 29 17 38 14  9]


In [11]:
arr=np.random.randint(-1000,1000,10)
res=np.array([])
print(arr)
res=np.where(arr>4)
print(res)

[-421 -857 -376  248 -917 -499 -926  610 -888  899]
(array([3, 7, 9]),)


In [4]:
#7Write a NumPy program to create a 1D array with random numbers and search a particular number 
#given by the user. 
import numpy as np
arr=np.random.randint(1,100,20)
print(arr)
num=int(input("enter number to search:"))
res=np.where(arr==num)
if len(res[0])>0:
    print("element found")
else:
    print("element not found")

[ 5 40 64 71  3 78 85 98 63 55 22 39 80 29 65 83 55 89 67 28]
element found


In [5]:
#8.Write a NumPy program to save a given array to a text file and load it.
#to save use np.savetxt to read np.readtxt

arr=np.array([1,2,3,4,5])
np.savetxt("mytext",arr)
print("file content is:")
np.loadtxt("mytext")


file content is:


array([1., 2., 3., 4., 5.])

In [6]:
#9.Write a NumPy program to create an array of all the even integers from 30 to 60.
arr=np.arange(30,61,2)
print(arr)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60]


In [8]:
#10. Write a NumPy program to compute sum of all elements ,sum of each column and sum of each row 
#of a given array.
#for row and column using axiz=0 and axis=1 for row and column
arr=np.array([
    [1,2,3],
    [4,5,6],
    [6,7,8]
])
print("array is:",arr)
sum=np.sum(arr)
column=np.sum(arr,axis=0)
row=np.sum(arr,axis=1)
print("sum=",sum,"column_sum=",column,"row_sum=",row)


 

array is: [[1 2 3]
 [4 5 6]
 [6 7 8]]
sum= 42 column_sum= [11 14 17] row_sum= [ 6 15 21]
