In [1]:
import numpy as np

In [19]:
#1.dot product of matrix
#for matrix operations we use linalg which is a NumPy’s Linear Algebra module.
#It contains all the important mathematical functions needed to perform matrix operations.

from numpy import linalg
def matrixread(n):
    matrix=[]
    for i in range(0,n):
        row=[]
        for j in range(0,n):
            num=int(input("enter element "+str(i)+","+str(j)))
            row.append(num)
        matrix.append(row)
    return matrix

n=int(input("enter the order of the matrix:"))
print("matrix:")
matrix1=np.array(matrixread(n))
print("matrix2:")
matrix2=np.array(matrixread(n))
print("the matrices are:")
print(matrix1)
print(matrix2)


matrix:
matrix2:
the matrices are:
[[1 2 3]
 [4 5 6]
 [1 2 3]]
[[6 7 8]
 [9 0 8]
 [7 6 5]]


In [29]:
#another method
r=int(input("enter the number of rows"))
c=int(input("enter the number of columns:"))

print("enter values pf matrix 1 (space sepatated)")
data1=list(map(int,input().split()))
matrix1=np.array(data1).reshape(r,c)

print("enter the matrix 2 elements:")
data2=list(map(int,input().split()))
matrix2=np.array(data2).reshape(r,c)

print(matrix1)
print(matrix2)

enter values pf matrix 1 (space sepatated)
enter the matrix 2 elements:
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [14]:
#dot product
dot=np.dot(matrix1,matrix2)
print(dot)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [15]:
#2.Transpose
print("transpose:",np.transpose(matrix1))

transpose: [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
#3.trace 
#sum of the diagonal elemnts of the square matrix
print("trace:",np.trace(dot))

trace: 189


In [ ]:
#4.rank
#linearly indpenedent rows or columns in the matrix
print("rank:",linalg.matrix_rank(matrix1))

rank: 2


In [21]:
#5.determinant
#“The determinant is a scalar value that shows whether a matrix is invertible.
#uses np.linalg.det to find det of a matrix
print("Determinant:",np.linalg.det(dot))

Determinant: -7.673861546209039e-13


In [ ]:
#6.Inverse
#The inverse of a matrix A is another matrix A⁻¹ such that A × A⁻¹ = I. A matrix is invertible only if its determinant is non-zero. We find the inverse using np.linalg.inv().”

print("Inverse:",np.linalg.inv(matrix2))

Inverse: [[-4.   3. ]
 [ 3.5 -2.5]]


In [ ]:
#7.Eigen values and eigen vectors
#Eigenvector is a direction that remains unchanged when the matrix acts on it, and the eigenvalue tells how much the eigenvector is scaled.
#We calculate them using np.linalg.eig() in NumPy.”
#np.linalg.eig() gives both vectors and values

print("eigen value:",linalg.eigvals(matrix1))

#if only eigen vectors
#_is used to ignore eigen values
_,eigenvectors=linalg.eig(matrix1)
print("eigenvectors:",eigenvectors)

eigen value: [-0.37228132  5.37228132]
eigenvectors: [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
